import { type MetadataRoute } from 'next'

// Required for static export: this is a route handler under the hood,
// and `output: 'export'` won't render it unless we opt into static.
export const dynamic = 'force-static'

// Web App Manifest — enables real PWA install on Android Chrome
// (full-app icon, splash, standalone window). iOS install is driven by
// the `appleWebApp` metadata in layout.tsx, not this manifest.
//
// Next emits this at /manifest.webmanifest at build time and injects the
// matching <link rel="manifest"> automatically.
//
// Icons: 192x192 and 512x512 PNGs (white background, in public/) drive
// the Android install icon and splash. The browser-tab favicon and the
// iOS home-screen icon come from src/app/icon.png and
// src/app/apple-icon.png respectively (Next file conventions), not here.
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: 'BOTA Toolbox',
    short_name: 'BOTA Toolbox',
    description:
      'An unofficial set of advanced tools for members of the Builders of the Adytum.',
    start_url: '/',
    display: 'standalone',
    // Matches the viewport themeColor in layout.tsx so the install
    // splash and the browser chrome agree.
    background_color: '#18181b',
    theme_color: '#18181b',
    lang: 'en',
    icons: [
      {
        src: '/icon-192.png',
        sizes: '192x192',
        type: 'image/png',
      },
      {
        src: '/icon-512.png',
        sizes: '512x512',
        type: 'image/png',
      },
      // Maskable variants (the glyph already sits inside the central
      // safe zone of the gradient tile) so Android's circle/squircle
      // crop never clips the artwork. Generated by `npm run gen:appicon`.
      {
        src: '/icon-maskable-192.png',
        sizes: '192x192',
        type: 'image/png',
        purpose: 'maskable',
      },
      {
        src: '/icon-maskable-512.png',
        sizes: '512x512',
        type: 'image/png',
        purpose: 'maskable',
      },
    ],
  }
}
