// Server-only helper for reading localized prose markdown. English
// bodies live at content/<kind>/<slug>.md; translations at
// content/<kind>/<locale>/<slug>.md (skeletons generated by
// `npm run gen:translations`). A missing translation falls back to the
// English file, so partially translated content always renders.
//
// Kept out of src/content/data/ on purpose: this touches node:fs, and
// the data barrel must stay safe to import from client components.

import { existsSync, readFileSync } from 'node:fs'
import { join } from 'node:path'

import { DEFAULT_LOCALE, type Locale } from '@/lib/locales'

export function readLocalizedMarkdown(
  kind: 'texts' | 'rituals',
  locale: Locale,
  slug: string,
): string {
  if (locale !== DEFAULT_LOCALE) {
    const localized = join(process.cwd(), 'content', kind, locale, `${slug}.md`)
    if (existsSync(localized)) return readFileSync(localized, 'utf8')
  }
  return readFileSync(
    join(process.cwd(), 'content', kind, `${slug}.md`),
    'utf8',
  )
}
