// Generates the iOS launch screens declared in src/lib/splash.ts:
// public/splash/apple-splash-{scheme}-{w}x{h}.png, one per device size
// per color scheme. The cube mark (public/icon-512.png) is composited
// onto a solid background, optically centered (45% height — dead center
// reads low to the eye).
//
// The icon artwork (regenerated by gen-appicon.ts from assets/cube.svg)
// is the cube on an Apple-style gradient tile. Both splash schemes show
// it with iOS's rounded-corner tile treatment, so the launch screen
// reads as "the app icon" centered on black/white — the native launch
// convention.
//
// Run with: npm run gen:splash  (then commit public/splash/)

import { mkdirSync } from 'node:fs'
import { join } from 'node:path'
import sharp from 'sharp'

import { SPLASH_DEVICES, SPLASH_SCHEMES, splashPath } from '../src/lib/splash.ts'

const ICON = join('public', 'icon-512.png')
const OUT_DIR = join('public', 'splash')

// Mark width as a fraction of the device's logical width — ~26% lands
// near the ~100pt a native launch icon occupies.
const MARK_FRACTION = 0.26
// iOS app-icon corner radius is ≈ 22.37% of the tile size.
const CORNER_FRACTION = 0.2237

async function roundedMark(sizePx: number): Promise<Buffer> {
  const radius = Math.round(sizePx * CORNER_FRACTION)
  const mask = Buffer.from(
    `<svg width="${sizePx}" height="${sizePx}"><rect width="${sizePx}" height="${sizePx}" rx="${radius}" ry="${radius}"/></svg>`,
  )
  return sharp(ICON)
    .resize(sizePx, sizePx)
    .composite([{ input: mask, blend: 'dest-in' }])
    .png()
    .toBuffer()
}

mkdirSync(OUT_DIR, { recursive: true })

for (const device of SPLASH_DEVICES) {
  const width = device.w * device.scale
  const height = device.h * device.scale
  const markPx = Math.round(device.w * MARK_FRACTION) * device.scale
  const mark = await roundedMark(markPx)

  for (const { scheme, bg } of SPLASH_SCHEMES) {
    const file = join('public', ...splashPath(scheme, device).split('/'))
    await sharp({
      create: { width, height, channels: 3, background: bg },
    })
      .composite([
        {
          input: mark,
          left: Math.round((width - markPx) / 2),
          top: Math.round(height * 0.45 - markPx / 2),
        },
      ])
      .png()
      .toFile(file)
    console.log(`gen-splash: ${file} (${width}x${height})`)
  }
}
